# Generated by Django 2.2.4 on 2020-03-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='AnnotationTags',
        ),
    ]
