# Generated by Django 2.2.13 on 2021-01-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hx_lti_initializer', '0002_auto_20200701_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticourse',
            name='course_admins',
            field=models.ManyToManyField(blank=True, related_name='course_admin_user_profiles', to='hx_lti_initializer.LTIProfile'),
        ),
    ]
