# Generated by Django 3.2.18 on 2023-03-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hx_lti_initializer', '0004_auto_20210608_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lticourse',
            options={'ordering': ['course_name', 'course_id'], 'verbose_name': 'Course'},
        ),
    ]
