# Generated by Django 4.2.30 on 2026-07-10 17:19

from django.db import migrations, models
import hx_lti_initializer.models


class Migration(migrations.Migration):

    dependencies = [
        ('hx_lti_initializer', '0008_lticoursecredential_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticoursecredential',
            name='lti_key',
            field=models.CharField(default=hx_lti_initializer.models._default_lti_key, max_length=255),
        ),
    ]
