# Generated by Django 3.2.18 on 2023-11-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hxat.apps.vpaljwt.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('secret', models.UUIDField(default=uuid.uuid4)),
                ('expire_on', models.DateTimeField(default=hxat.apps.vpaljwt.models.expire_in_weeks)),
                ('valid_for_secs', models.PositiveSmallIntegerField(default=hxat.apps.vpaljwt.models.expire_in_secs)),
                ('audience', models.JSONField(default=hxat.apps.vpaljwt.models.empty_list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
