# Generated by Django 2.2.3 on 2019-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hx_lti_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='use_hxighlighter',
            field=models.BooleanField(default=False),
        ),
    ]
